export default [
	{
		'id': 0,
		'name': 'Spear Chugger',
		'graphic': 'img/kodama_spritesheet.png',
		'projectile': 'img/arrow_projectile.png',
		'damage': 5,
		'range': 350,
		'cooldown': 1000,
		'slow': false,
		'blast': 0,
	},
	{
		'id': 1,
		'name': 'Slime Thrower',
		'graphic': 'img/kodama_spritesheet.png',
		'projectile': 'img/arrow_projectile.png',
		'damage': 4,
		'range': 350,
		'cooldown': 1500,
		'slow': true,
		'blast': 0,
	},
	{
		'id': 2,
		'name': 'Bomb Hauler',
		'graphic': 'img/kodama_aoe_spritesheet.png',
		'projectile': 'img/arrow_projectile.png',
		'damage': 3,
		'range': 350,
		'cooldown': 1000,
		'slow': false,
		'blast': 100,
	},
	{
		'id': 3,
		'name': 'Precision Leafer',
		'graphic': 'img/kodama_spritesheet.png',
		'projectile': 'img/arrow_projectile.png',
		'damage': 8,
		'range': 550,
		'cooldown': 2000,
		'slow': false,
		'blast': 0,
	},
]