export default [
	{
		'id': 0,
		'name': 'Spear Chugger',
		'description': 'The humble default. Average speed, range and damage.',
		'graphic': 'img/kodama_spritesheet.png',
		'projectile': 'img/arrow_projectile.png',
		'ui': '1_spear',
		'damage': 5,
		'range': 350,
		'cooldown': 1000,
		'slow': false,
		'blast': 0,
		'cost': {sun: 1, water: 1},
	},
	{
		'id': 2,
		'name': 'Bomb Hauler',
		'description': 'Slow firing and less damage than the default but damages a whole area instead of one bug!',
		'graphic': 'img/kodama_aoe_spritesheet.png',
		'projectile': 'img/arrow_projectile.png',
		'ui': '2_aoe',
		'damage': 3,
		'range': 350,
		'cooldown': 1000,
		'slow': false,
		'blast': 100,
		'cost': {sun: 2, water: 2},
	},
	{
		'id': 1,
		'name': 'Slime Thrower',
		'description': 'Less damage, slower rate of fire but slows down any enemy that was hit.',
		'graphic': 'img/kodama_spritesheet.png',
		'projectile': 'img/arrow_projectile.png',
		'ui': '3_slow',
		'damage': 4,
		'range': 350,
		'cooldown': 1500,
		'slow': true,
		'blast': 0,
		'cost': {sun: 3, water: 3},
	},
	{
		'id': 3,
		'name': 'Precision Leafer',
		'description': 'True long range specialist! Slowest rate of fire but highest damage and longest range.',
		'graphic': 'img/kodama_spritesheet.png',
		'projectile': 'img/arrow_projectile.png',
		'ui': '4_sniper',
		'damage': 8,
		'range': 550,
		'cooldown': 2000,
		'slow': false,
		'blast': 0,
		'cost': {sun: 33, water: 33},
	},
]